sdk: '2'
language: java
go-runtime:
  version: '1.12-alpine'
native:
  image: 'openjdk:8u181-jre-alpine'
  static:
    - path: 'native.sh'
      dest: 'native'
  build:
    image: 'openjdk:8u181-slim'
    deps:
      - 'apt update && apt install -y maven'
    run:
      - 'mvn package'
    artifacts:
      - path: '/native/target/native-jar-with-dependencies.jar'
  test:
    run:
      - 'mvn test'
